SELECT BOOK_LOANS.BranchID, BranchName, BookID, COUNT(BOOK_LOANS.BranchID)
FROM dbo.LIBRARY_BRANCH INNER JOIN dbo.BOOK_LOANS
ON dbo.LIBRARY_BRANCH.BranchID = dbo.BOOK_LOANS.BranchID
GROUP BY BOOK_LOANS.BranchID, BranchName, BookID
HAVING (COUNT(BOOK_LOANS.BranchID) > 1)
